version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: alex
